config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :project_histories, only: [:create, :new]
  end
  resources :comments
  resources :statuses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  validates :content, presence: true

  has_one :project_history, as: :actionable
  has_one :project, through: :project_history
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true

  has_many :project_histories
  has_many :comments, lambda {
                        where(project_histories: { actionable_type: 'Comment' })
                      }, through: :project_histories, source: :actionable, source_type: 'Comment'
  has_many :statuses, lambda {
                        where(project_histories: { actionable_type: 'Status' })
                      }, through: :project_histories, source: :actionable, source_type: 'Status'

  def most_recent_status
    statuses.order(created_at: :desc).limit(1).first&.name
  end
end

app/models/project_history.rb
class ProjectHistory < ApplicationRecord
  belongs_to :actionable, polymorphic: true
  belongs_to :project
end

app/models/status.rb
# frozen_string_literal: true

class Status < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :project_histories, as: :actionable
  has_many :projects, through: :project_histories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params.slice(:content))
    
    ActiveRecord::Base.transaction do
      @project = Project.find(comment_params[:project_id])
      if @comment.save
        @project.project_histories.create(actionable: @comment)
        redirect_to @project, notice: 'Comment was successfully created.'
      else
        render 'projects/show'
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content, :project_id)
    end
end

app/controllers/project_histories_controller.rb
class ProjectHistoriesController < ApplicationController
  def new
    @project = Project.find(params[:project_id])
    @project_history = @project.project_histories.build
  end

  def create
    @project = Project.find(params[:project_id])
    @project_history = @project.project_histories.build(project_history_params)

    if @project_history.save
      redirect_to @project, notice: 'Project history was successfully created.'
    else
      render :new
    end
  end

  private

  def project_history_params
    params.require(:project_history).permit(:actionable_id, :actionable_type)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    @project_histories = @project.project_histories.order(:asc)
    @project_history = @project.project_histories.new
    @comment = Comment.new
    @statuses = Status.all
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.joins("LEFT JOIN project_histories ON project_histories.project_id = projects.id")
                      .joins("LEFT JOIN comments ON comments.id = project_histories.actionable_id AND project_histories.actionable_type = 'Comment'")
                      .joins("LEFT JOIN statuses ON statuses.id = project_histories.actionable_id AND project_histories.actionable_type = 'Status'")
                      .find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: %i[ show edit update destroy ]

  # GET /statuses or /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1 or /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses or /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to status_url(@status), notice: "Status was successfully created." }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1 or /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to status_url(@status), notice: "Status was successfully updated." }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1 or /statuses/1.json
  def destroy
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url, notice: "Status was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def status_params
      params.require(:status).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Content:</strong>
    <%= comment.content %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-slate-200">
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="w-full">
    <%= form.text_field :title, class: "title bg-gray-100 border border-gray-300 p-2 mb-4 outline-none w-full", placeholder: "Title" %>
  </div>

    <%= form.text_area :description, class: "description bg-gray-100 sec p-3 h-60 border border-gray-300 outline-none w-full", placeholder: "Description" %>

  <div class="buttons  btn border border-indigo-500 p-1 px-4 font-semibold cursor-pointer text-gray-200 ml-2 bg-indigo-500">
    <%= form.submit class: "cursor-pointer" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <h5
    class="mb-2 text-xl font-medium leading-tight text-neutral-800 dark:text-neutral-50">
    <%= project.title %>
  </h5>
  <p class="mb-4 text-base dark:text-neutral-200 text-green-600">
    Status:
    <%= project.most_recent_status %>
  </p>
  <p class="mb-4 text-base text-neutral-600 dark:text-neutral-200">
    <%= project.description %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="w-[800px] rounded overflow-hidden shadow-lg w-full bg-slate-100 mx-auto">
  <h1 class="text-2xl m-3.5">Projects</h1>
  <%= link_to "New project", new_project_path, class: "inline-block hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded mb-3" %>
  <% @projects.each do |project| %>
    <div
    class="block rounded-lg bg-white p-6 shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)] dark:bg-neutral-700 w-[800px]">
      <%= render project %>
      <%= link_to "Show this project", project, class: "inline-block hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded m-auto" %>
    </div>
  <% end %>
</div>

app/views/projects/new.html.erb
<div class="editor mx-auto w-10/12 flex flex-col text-gray-800 border border-gray-300 p-4 shadow-lg max-w-2xl bg-white">
  <div class="block heading text-center font-bold text-2xl m-5 text-gray-800">New Project</div>

  <%= render "form", project: @project %>

  <br>

  <div>
    <%= link_to "Back to projects", projects_path, class: "btn border border-gray-300 p-1 px-4 font-semibold cursor-pointer text-gray-500 ml-auto" %>
  </div>
</div>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="rounded overflow-hidden shadow-lg w-full bg-slate-100  mx-auto">
  <div
    class="block rounded-lg bg-white p-6 shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)] dark:bg-neutral-700 w-[800px] mx-auto">
    <%= render @project %>
    
    <div>
      <%= link_to "Edit this project", edit_project_path(@project) %> |
      <%= link_to "Back to projects", projects_path %>

      <%= button_to "Destroy this project", @project, method: :delete %>
    </div>

    <h2>Change Status</h2>

    <%= form_for [@project, @project.project_histories.build] do |f| %>
      <%= f.hidden_field :actionable_type, value: 'Status' %>
      <%= f.label :status_id %>
      <%= f.collection_select :actionable_id, @statuses || [], :id, :name %>
      <%= f.submit 'Update Status', class: 'btn btn-primary' %>
    <% end %>

    <section class="bg-white dark:bg-gray-900 py-8 lg:py-16">
      <div class="max-w-2xl mx-auto px-4">
        <div class="flex justify-between items-center mb-6">
          <h2 class="text-lg lg:text-2xl font-bold text-gray-900 dark:text-white">Discussions and status updates (<%= @project_histories&.count || 0 %>)</h2>
        </div>
        <%= form_with(model: @comment, url: comments_path, method: :post, class: "mb-6") do |form| %>
          <%= form.hidden_field :project_id, value: @project.id %>
          <div class="py-2 px-4 mb-4 bg-white rounded-lg rounded-t-lg border border-gray-200 dark:bg-gray-800 dark:border-gray-700">
          <%= form.label :content, 'Your comment', class: "sr-only" %>
          <%= form.text_area :content, rows: '6', class: "px-0 w-full text-sm text-gray-900 border-0 focus:ring-0 focus:outline-none dark:text-white dark:placeholder-gray-400 dark:bg-gray-800", placeholder: "Write a comment...", required: true %>
          </div>
          <%= form.submit 'Add Comment', class: "buttons inline-flex items-center py-2.5 px-4 text-xs font-medium text-center text-white bg-blue-700 rounded-lg focus:ring-4 focus:ring-primary-200 dark:focus:ring-primary-900 hover:bg-primary-800 cursor-pointer" %>
        <% end %>

        <% @project_histories && @project_histories.each do |project_history| %>
          <% if project_history.actionable_type == 'Status' %>
            <article class="p-6 mb-6 text-base bg-white border-t border-gray-200 dark:border-gray-700 dark:bg-gray-900">
              <p class="text-sm text-gray-600 dark:text-gray-400"><span class="text-green-800">Status update: <%= project_history.actionable.name %></span><time pubdate datetime=<%= "#{project_history.created_at.to_formatted_s(:short_db)}"%> title=<%= "#{project_history.created_at.to_formatted_s(:short_ordinal)}"%>> <%= project_history.created_at.to_formatted_s(:short_ordinal)%></time></p>
            </article>
          <% end %>

          <% if project_history.actionable_type == 'Comment' %>
            <article class="p-6 mb-6 text-base bg-white border-t border-gray-200 dark:border-gray-700 dark:bg-gray-900">
              <footer class="flex justify-between items-center mb-2">
                  <div class="flex items-center">
                      <p class="inline-flex items-center mr-3 text-sm text-gray-900 dark:text-white"><img
                              class="mr-2 w-6 h-6 rounded-full"
                              src="https://flowbite.com/docs/images/people/profile-picture-3.jpg"
                              alt="Bonnie Green">Bonnie Green</p>
                      <p class="text-sm text-gray-600 dark:text-gray-400"><time pubdate datetime=<%= "#{project_history.created_at.to_formatted_s(:short_db)}"%>
                              title=<%= "#{project_history.created_at.to_formatted_s(:short_ordinal)}"%>> <%= project_history.created_at.to_formatted_s(:short_ordinal)%></time></p>
                  </div>
              </footer>
              <p class="text-gray-500 dark:text-gray-400"><%= project_history.actionable.content %></p>
            </article>
          <% end %>
        <% end %>
      </div>
    </section>
  </div>
</div>

app/views/statuses/_form.html.erb
<%= form_with(model: status) do |form| %>
  <% if status.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
        <% status.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/statuses/_status.html.erb
<div id="<%= dom_id status %>">
  <p>
    <strong>Name:</strong>
    <%= status.name %>
  </p>

</div>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render "form", status: @status %>

<br>

<div>
  <%= link_to "Show this status", @status %> |
  <%= link_to "Back to statuses", statuses_path %>
</div>

app/views/statuses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Statuses</h1>

<div id="statuses">
  <% @statuses.each do |status| %>
    <%= render status %>
    <p>
      <%= link_to "Show this status", status %>
    </p>
  <% end %>
</div>

<%= link_to "New status", new_status_path %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render "form", status: @status %>

<br>

<div>
  <%= link_to "Back to statuses", statuses_path %>
</div>

app/views/statuses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @status %>

<div>
  <%= link_to "Edit this status", edit_status_path(@status) %> |
  <%= link_to "Back to statuses", statuses_path %>

  <%= button_to "Destroy this status", @status, method: :delete %>
</div>